In [1]:
import hmac
import hashlib
import numpy as np
import pandas as pd
from math import pow, floor
from datetime import datetime, timedelta
from time import sleep

<h1> Data Set with 10 million rows </h1>

In [2]:
df = pd.read_pickle('data/data.pkl')

In [3]:
df

,points,seeds,hmacs
0,1.29,492bd10144a3525e2745718fe4d25e08affbea483872d8...,3a64c94ef096cf1cd96ba8eb8f913be89464a0c284daf7...
1,3.14,07d922bcfbf90c15fe50bb5d9aa84549e1131c97cf0a58...,af0d01b75e876e2df0b48624cbf55e96b08e90e7ddef10...
2,1.98,d845b7ec2d9399db49ccd972753e2e764cccb204711829...,7f6100e884422445443bd8b2c1a8b2b3af9de17c09e02b...
3,2.38,994bf7fbd9978adc70cbe1d681e7080eb65656edaa597c...,95378c4328466421ddf2250aeeff86c2fea51f99395e7f...
4,0.00,f29d1af249659b527af6d0c846a7552cda497318d43d73...,fd34e6cd930a371c8bde9a109d8caaa301aeaca81eba7f...
...,...,...,...
9999996,0.00,cb1bcaf8452bd7a8d64833b5ceedc47f3859e95f90d800...,3509229d18125330b9f2840412a273776a2696ca019a66...
9999997,4.58,8a8603b175b949f71b14a11996b6a3af1abdd706dccef7...,c8a8f59d4d44f9fafe5dd776aa21c2bad12d7ef9a55eb5...
9999998,5.53,81884102275b432f2a6083eadd74c9059c7db58bad0bfa...,d228c25ea402d18aa9b779a0d8cef2a4325137b301f418...
9999999,3.35,ebf4cb25765d637f9c2714e3bac1a3833a5d81c936394e...,b44bb1a99fbe6b2396a4b7c29ae0571167be104da5ac4b...
10000000,1.49,638d0a8f124aa3a85cbcf828019796e62060166d3392ad...,558c0057ecd89af2347a8a0b718c862747990e8400dce4...

<h2>Dataset may, 18ยบ 12:49 gmt-3</h2>

In [4]:
generated = pd.read_pickle('data/da0518-main.pkl')
generated[1000:]

,points,seeds,hmacs
1000,1.28,6af4ddc50c17736d83ae3a7af87e1fa8aa4950ab5a5be5...,398ad25e1ba1acf609227ccec5a288de02f57c66f1bf66...
1001,8.74,337979975c4fbf3f609463262d3c54b4f0832a34244b8f...,e2fef25e2851d7b3ce558b4101785db588de909b284e61...
1002,46.04,2222dba2850bb37ed866ad4b9c134c5a4e02440d1580d2...,fa7ebfc4413bdf6b3258b1059d7c6336904e655b575ed7...
1003,2.43,09e7635c92a1e2348a56dc81ff80cae8446983f74f9a40...,979eddc257f2fb083ce590e8adbc13212fdcb26fb21d06...
1004,5.38,2c2f2458714146e74fc4ec947c9cb089cb44b195802248...,d0dd2eb6d6a7ec1c4a4db1a1441b6a5d1e082778b2f7ba...
...,...,...,...
1995,1.63,bad24928b37392c9cfbaf6561cc237a38e058eb937607f...,63c14ecc7ee695901ee73b90faf8cbe7f90d5b73a017e1...
1996,1.15,54a8a69cabcca6737fb4cca6f4932127c90cd5ff4d29a9...,22de508599b49f3b24f4d8de49376a6cde24c843d6f11f...
1997,1.00,efe9531161362229b70919281d39ec378a86c0c5524865...,01f26bf26f2064b236841dcf4316d2d59cf546fdc60bb7...
1998,1.19,8efccb83b9f6f284bba66f1b526d15c0ff4baa73c64348...,29f46256f21f8bd4d6e2d95c679b759a160339f48f51c6...
1999,1.13,b52e9eb78b4078504d3716b957784068711f59e1a86e0f...,1ed77732be044b422f416fb4ebb85b539742a04d6cfa01...

In [5]:
worked = pd.read_pickle('data/da0518-stats.pkl')

worked

,out,in,dif,insum,insuMin,insuMax,inprop,good,good100sum,good100min,good100max
0,1.67,1.28,-0.39,336.74,336.35,935.23,0.000651,0,40.0,35.0,42.0
1,1.67,8.74,7.07,343.81,336.35,935.23,0.012457,1,41.0,35.0,42.0
2,1.33,46.04,44.71,388.52,336.35,935.23,0.087113,1,42.0,35.0,42.0
3,1.76,2.43,0.67,389.19,336.35,935.23,0.088231,1,43.0,35.0,43.0
4,1.15,5.38,4.23,393.42,336.35,935.23,0.095295,1,44.0,35.0,44.0
...,...,...,...,...,...,...,...,...,...,...,...
995,1.05,1.63,0.58,963.44,400.64,1009.22,0.924776,0,50.0,37.0,52.0
996,5.09,1.15,-3.94,959.50,400.64,1009.22,0.918302,0,49.0,37.0,52.0
997,6.68,1.00,-5.68,953.82,400.64,1009.22,0.908968,0,48.0,37.0,52.0
998,1.82,1.19,-0.63,953.19,400.64,1009.22,0.907933,0,48.0,37.0,52.0
999,1.24,1.13,-0.11,953.08,400.64,1009.22,0.907752,0,48.0,37.0,52.0

In [14]:
p = df.points #convenience

In [43]:
delimi = [0,1.1]
see = []
for x in range(98):
    delimi.append(x+2)

# delimi

In [46]:
for x in range(len(delimi)):
    if x == (len(delimi)-1):
        proportion = p[p >= delimi[x]].count() / len(df) * 100
        print(f"{proportion:.4f}% de {delimi[x]} a em diante")
    else:
        proportion = p[(p >= delimi[x]) & (p < delimi[x+1])].count() / len(df) * 100
        print(f"{proportion:.4f}% de {delimi[x]} a {delimi[x+1]}")

15.2316% de 0 a 1.1
38.3463% de 1.1 a 2
15.5237% de 2 a 3
7.7285% de 3 a 4
4.6369% de 4 a 5
3.0890% de 5 a 6
2.2032% de 6 a 7
1.6595% de 7 a 8
1.2889% de 8 a 9
1.0310% de 9 a 10
0.8390% de 10 a 11
0.7033% de 11 a 12
0.5934% de 12 a 13
0.5062% de 13 a 14
0.4398% de 14 a 15
0.3839% de 15 a 16
0.3395% de 16 a 17
0.3041% de 17 a 18
0.2723% de 18 a 19
0.2436% de 19 a 20
0.2217% de 20 a 21
0.1977% de 21 a 22
0.1842% de 22 a 23
0.1712% de 23 a 24
0.1551% de 24 a 25
0.1419% de 25 a 26
0.1303% de 26 a 27
0.1230% de 27 a 28
0.1142% de 28 a 29
0.1082% de 29 a 30
0.0981% de 30 a 31
0.0922% de 31 a 32
0.0900% de 32 a 33
0.0823% de 33 a 34
0.0779% de 34 a 35
0.0749% de 35 a 36
0.0702% de 36 a 37
0.0655% de 37 a 38
0.0615% de 38 a 39
0.0595% de 39 a 40
0.0568% de 40 a 41
0.0531% de 41 a 42
0.0513% de 42 a 43
0.0489% de 43 a 44
0.0473% de 44 a 45
0.0457% de 45 a 46
0.0432% de 46 a 47
0.0405% de 47 a 48
0.0406% de 48 a 49
0.0391% de 49 a 50
0.0363% de 50 a 51
0.0352% de 51 a 52
0.0327% de 52 a 53
0.0331% de 53 a 54
0.0308% de 54 a 55
0.0308% de 55 a 56
0.0289% de 56 a 57
0.0285% de 57 a 58
0.0269% de 58 a 59
0.0275% de 59 a 60
0.0250% de 60 a 61
0.0239% de 61 a 62
0.0228% de 62 a 63
0.0224% de 63 a 64
0.0223% de 64 a 65
0.0220% de 65 a 66
0.0217% de 66 a 67
0.0206% de 67 a 68
0.0196% de 68 a 69
0.0199% de 69 a 70
0.0184% de 70 a 71
0.0178% de 71 a 72
0.0179% de 72 a 73
0.0167% de 73 a 74
0.0167% de 74 a 75
0.0162% de 75 a 76
0.0158% de 76 a 77
0.0157% de 77 a 78
0.0149% de 78 a 79
0.0152% de 79 a 80
0.0143% de 80 a 81
0.0141% de 81 a 82
0.0133% de 82 a 83
0.0140% de 83 a 84
0.0129% de 84 a 85
0.0127% de 85 a 86
0.0126% de 86 a 87
0.0119% de 87 a 88
0.0118% de 88 a 89
0.0111% de 89 a 90
0.0112% de 90 a 91
0.0116% de 91 a 92
0.0108% de 92 a 93
0.0099% de 93 a 94
0.0102% de 94 a 95
0.0105% de 95 a 96
0.0098% de 96 a 97
0.0095% de 97 a 98
0.0097% de 98 a 99
0.9319% de 99 a em diante

In [48]:
for x in range(len(delimi)):
    if x == (len(delimi)-1):
        proportion = p[p >= delimi[x]].count()
        print(f"{proportion:,} de {delimi[x]} a em diante")
    else:
        proportion = p[(p >= delimi[x]) & (p < delimi[x+1])].count()
        print(f"{proportion:,} de {delimi[x]} a {delimi[x+1]}")

1,523,159 de 0 a 1.1
3,834,626 de 1.1 a 2
1,552,369 de 2 a 3
772,851 de 3 a 4
463,695 de 4 a 5
308,896 de 5 a 6
220,316 de 6 a 7
165,951 de 7 a 8
128,894 de 8 a 9
103,102 de 9 a 10
83,905 de 10 a 11
70,331 de 11 a 12
59,336 de 12 a 13
50,620 de 13 a 14
43,980 de 14 a 15
38,389 de 15 a 16
33,950 de 16 a 17
30,406 de 17 a 18
27,226 de 18 a 19
24,359 de 19 a 20
22,167 de 20 a 21
19,766 de 21 a 22
18,423 de 22 a 23
17,122 de 23 a 24
15,507 de 24 a 25
14,195 de 25 a 26
13,027 de 26 a 27
12,299 de 27 a 28
11,418 de 28 a 29
10,822 de 29 a 30
9,815 de 30 a 31
9,220 de 31 a 32
8,996 de 32 a 33
8,230 de 33 a 34
7,788 de 34 a 35
7,487 de 35 a 36
7,020 de 36 a 37
6,555 de 37 a 38
6,155 de 38 a 39
5,951 de 39 a 40
5,677 de 40 a 41
5,308 de 41 a 42
5,135 de 42 a 43
4,893 de 43 a 44
4,734 de 44 a 45
4,568 de 45 a 46
4,320 de 46 a 47
4,046 de 47 a 48
4,059 de 48 a 49
3,908 de 49 a 50
3,632 de 50 a 51
3,516 de 51 a 52
3,275 de 52 a 53
3,313 de 53 a 54
3,077 de 54 a 55
3,085 de 55 a 56
2,894 de 56 a 57
2,846 de 57 a 58
2,690 de 58 a 59
2,749 de 59 a 60
2,502 de 60 a 61
2,388 de 61 a 62
2,283 de 62 a 63
2,238 de 63 a 64
2,231 de 64 a 65
2,198 de 65 a 66
2,168 de 66 a 67
2,056 de 67 a 68
1,959 de 68 a 69
1,994 de 69 a 70
1,838 de 70 a 71
1,782 de 71 a 72
1,786 de 72 a 73
1,670 de 73 a 74
1,675 de 74 a 75
1,625 de 75 a 76
1,583 de 76 a 77
1,571 de 77 a 78
1,488 de 78 a 79
1,518 de 79 a 80
1,432 de 80 a 81
1,409 de 81 a 82
1,335 de 82 a 83
1,397 de 83 a 84
1,287 de 84 a 85
1,275 de 85 a 86
1,257 de 86 a 87
1,192 de 87 a 88
1,179 de 88 a 89
1,115 de 89 a 90
1,123 de 90 a 91
1,161 de 91 a 92
1,085 de 92 a 93
986 de 93 a 94
1,025 de 94 a 95
1,055 de 95 a 96
977 de 96 a 97
949 de 97 a 98
968 de 98 a 99
93,192 de 99 a em diante

In [40]:
p[p >= 2.2].count() / len(df) * 100

42.17399578260042

In [41]:
p[p < 2.2].count() / len(df) * 100

57.82600421739957

In [49]:
df2 = pd.read_pickle('data/da0528.pkl')